# Railway.toml

[services]
service_name = "java-app"

[services.java-app]
# Command to build the Java project using Maven
build = "mvn clean package"
# Command to start the Java application using the JAR file
start = "java -jar target/your-app-name-1.0.0.jar"
